# Generated by Django 5.0.3 on 2024-05-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studen',
            options={'managed': False},
        ),
    ]
