# Generated by Django 5.0.3 on 2024-05-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogn', '0002_alter_file_options_alter_mark_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='cogn_file',
        ),
        migrations.AlterModelTable(
            name='mark',
            table='cogn_mark',
        ),
        migrations.AlterModelTable(
            name='studen',
            table='cogn_studen',
        ),
    ]
