# Generated by Django 5.0.3 on 2024-05-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogn', '0003_alter_file_table_alter_mark_table_alter_studen_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gruppa1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cogn.group'),
        ),
    ]
