# Generated by Django 5.0.3 on 2024-05-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogn', '0005_student_metric7_student_metric8_student_metric9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='metric1',
            new_name='IQ',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric2',
            new_name='obr_pam',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric3',
            new_name='predl',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric4',
            new_name='prim_predm',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric5',
            new_name='rawen',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric6',
            new_name='sluh_pam',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric7',
            new_name='vnim_ob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric8',
            new_name='vnim_ust',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='metric9',
            new_name='vospr_prost',
        ),
    ]
