# Generated by Django 5.0.3 on 2024-05-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogn', '0006_rename_metric1_student_iq_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sluh_pam',
            new_name='rawen1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rawen',
            new_name='sluh_pam1',
        ),
    ]
